### ISSUE TITLE
Spawning `app`...                          Instrumenting...                                         Error: Objective-C runtime is not available

### ISSUE THREAD

**Issue by Mohamed3bdelwahab** [ivanhrabcak/frida-request-logging#1]
i got this errors  when try run it with any app

Spawning `app`...          
                Instrumenting...                                        
Error: Objective-C runtime is not available

**Comment by ivanhrabcak** [comment]
Are you using a modified sideloaded app? The frida tweak? What iOS version? Does any other frida functionality or hook work?

**Comment by Mohamed3bdelwahab** [comment]
android  11
 i try to run it on termux  rooted phone

**Comment by ivanhrabcak** [comment]
This hook unfortunately only works on iOS.
